// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GYM_BE.ENTITIES
{
    [Index("ROOM_ID", Name = "IX_AD_BOOKING_ROOM_ID")]
    public partial class AD_BOOKING
    {
        [Key]
        public long ID { get; set; }
        public long EMP_ID { get; set; }
        public long ROOM_ID { get; set; }
        public DateTime BOOKING_DAY { get; set; }
        public DateTime HOUR_FROM { get; set; }
        public DateTime HOUR_TO { get; set; }
        [StringLength(1500)]
        public string NOTE { get; set; }
        public long STATUS_ID { get; set; }
        public long? APPROVED_ID { get; set; }
        public DateTime? APPROVED_DATE { get; set; }
        [StringLength(1500)]
        public string APPROVED_NOTE { get; set; }
        [StringLength(450)]
        public string CREATE_BY { get; set; }
        [StringLength(450)]
        public string UPDATED_BY { get; set; }
        public DateTime? CREATE_DATE { get; set; }
        public DateTime? UPDATED_DATE { get; set; }
    }
}