// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GYM_BE.ENTITIES
{
    public partial class AD_PROGRAMS
    {
        [Key]
        public int PROGRAM_ID { get; set; }
        [StringLength(255)]
        public string CODE { get; set; }
        [StringLength(255)]
        public string NAME { get; set; }
        [StringLength(255)]
        public string PROGRAM_TYPE { get; set; }
        [StringLength(255)]
        public string DESCRIPTION { get; set; }
        [StringLength(255)]
        public string STORE_EXECUTE_IN { get; set; }
        [StringLength(255)]
        public string STORE_EXECUTE_OUT { get; set; }
        [StringLength(255)]
        public string TEMPLATE_NAME { get; set; }
        [StringLength(255)]
        public string TEMPLATE_TYPE_IN { get; set; }
        [StringLength(255)]
        public string TEMPLATE_TYPE_OUT { get; set; }
        [StringLength(500)]
        public string TEMPLATE_URL { get; set; }
        public int? PRIORITY { get; set; }
        public int? ORDERBY { get; set; }
        public int? SIZE { get; set; }
        public int? ORIENTATION { get; set; }
        public int? STATUS { get; set; }
        public int? PERMISSION { get; set; }
        [StringLength(255)]
        public string CREATED_BY { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CREATED_DATE { get; set; }
        [StringLength(255)]
        public string MODIFIED_BY { get; set; }
        [Column(TypeName = "date")]
        public DateTime? MODIFIED_DATE { get; set; }
        [StringLength(255)]
        public string CREATED_LOG { get; set; }
        [StringLength(255)]
        public string MODIFIED_LOG { get; set; }
        public int? OUTPUTFILE_SIZE { get; set; }
        [StringLength(255)]
        public string NLS_LANGUAGE { get; set; }
        [StringLength(255)]
        public string NLS_TERRITORY { get; set; }
        [StringLength(255)]
        public string PRINTER { get; set; }
        public int? DATESET_IN_REPORT { get; set; }
        [StringLength(255)]
        public string FILE_OUT_NAME { get; set; }
        public int? MODULE_ID { get; set; }
        public int? GROUP_ID { get; set; }
        public int? PROGRAM_TYPE_ID { get; set; }
        [StringLength(500)]
        public string SQLLOADER_FILE { get; set; }
        public int? LINE_FROM { get; set; }
        public int? IS_RUN_AFTER_COMPLETE { get; set; }
        public int? ISOLATION_PROGRAM { get; set; }
        public int? ISOLATION_USER { get; set; }
        public int? COLUMN_FROM { get; set; }
        public int? COLUMN_TO { get; set; }
        [StringLength(255)]
        public string EXPORT_STORE_EXECUTE { get; set; }
        [StringLength(255)]
        public string NAME_EN { get; set; }
    }
}