// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GYM_BE.ENTITIES
{
    public partial class AD_REQUEST_PARAMETERS
    {
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? REQUEST_ID { get; set; }
        [StringLength(255)]
        public string PARAMETER_NAME { get; set; }
        public string VALUE { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? SEQUENCE { get; set; }
        [Key]
        [Column(TypeName = "numeric(18, 0)")]
        public decimal ID { get; set; }
        [StringLength(255)]
        public string REPORT_FIELD { get; set; }
    }
}