// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GYM_BE.ENTITIES
{
    public partial class AD_REQUESTS_QUEUES
    {
        [Key]
        public long REQUEST_ID { get; set; }
        public int? PROGRAM_ID { get; set; }
        [StringLength(255)]
        public string PHASE_CODE { get; set; }
        [StringLength(255)]
        public string STATUS_CODE { get; set; }
        [Column(TypeName = "date")]
        public DateTime? START_DATE { get; set; }
        [Column(TypeName = "date")]
        public DateTime? END_DATE { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ACTUAL_START_DATE { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ACTUAL_COMPLETE_DATE { get; set; }
        public int? OUTPUTFILE_SIZE { get; set; }
        [StringLength(255)]
        public string NLS_LANGUAGE { get; set; }
        [StringLength(255)]
        public string NLS_TERRITORY { get; set; }
        [StringLength(255)]
        public string PRINTER { get; set; }
        public int? size { get; set; }
        public int? ORIENTATION { get; set; }
        public int? PERMISSION { get; set; }
        [StringLength(255)]
        public string CREATED_BY { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CREATED_DATE { get; set; }
        [StringLength(255)]
        public string MODIFIED_BY { get; set; }
        [Column(TypeName = "date")]
        public DateTime? MODIFIED_DATE { get; set; }
        [StringLength(255)]
        public string CREATED_LOG { get; set; }
        [StringLength(255)]
        public string MODIFIED_LOG { get; set; }
        [StringLength(255)]
        public string STORE_EXECUTE_IN { get; set; }
        [StringLength(255)]
        public string STORE_EXECUTE_OUT { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? PRIORITY { get; set; }
        [Column(TypeName = "ntext")]
        public string LOG_FILE { get; set; }
        [StringLength(255)]
        public string TEMPLATE_NAME { get; set; }
        [StringLength(255)]
        public string TEMPLATE_TYPE_IN { get; set; }
        [StringLength(255)]
        public string TEMPLATE_TYPE_OUT { get; set; }
        [StringLength(500)]
        public string TEMPLATE_URL { get; set; }
        [StringLength(255)]
        public string FILE_OUT_URL { get; set; }
        [StringLength(255)]
        public string FILE_OUT_NAME { get; set; }
        [StringLength(255)]
        public string CSV_FILE { get; set; }
        public int? TRY_COUNT { get; set; }
    }
}