// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Options;

namespace GYM_BE.ENTITIES
{
    public partial class FullDbContext : DbContext
    {
        public AppSettings _appSettings;

        public FullDbContext()
        {
        }

        public FullDbContext(DbContextOptions<FullDbContext> options, IOptions<AppSettings> appSettings)
            : base(options)
        {
            _appSettings = appSettings.Value;
        }

        public virtual DbSet<AD_BOOKING> AD_BOOKING { get; set; }
        public virtual DbSet<AD_PROGRAMS> AD_PROGRAMS { get; set; }
        public virtual DbSet<AD_REQUESTS> AD_REQUESTS { get; set; }
        public virtual DbSet<AD_REQUESTS_QUEUES> AD_REQUESTS_QUEUES { get; set; }
        public virtual DbSet<AD_REQUEST_PARAMETERS> AD_REQUEST_PARAMETERS { get; set; }
        public virtual DbSet<TR_CENTER> TrCenters { get; set; }

        protected override void ConfigureConventions(
        ModelConfigurationBuilder configurationBuilder)
        {
            configurationBuilder.Properties<decimal>()
                .HavePrecision(18, 9);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(_appSettings.ConnectionStrings.CoreDb);
            optionsBuilder.EnableSensitiveDataLogging();
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }
}